## testing
# protocol: "http"
# host: "localhost"
# port: "8080"

# production
protocol: "https"
host: "tabpfn-server-wjedmz7r5a-ez.a.run.app"
# host: tabpfn-server-preprod-wjedmz7r5a-ez.a.run.app   # preprod
port: "443"
endpoints:
  root:
    path: "/"
    methods: [ "GET" ]
    description: "Root endpoint"

  password_policy:
    path: "/auth/password_policy/"
    methods: [ "GET" ]
    description: "Password policy"

  validate_email:
    path: "/auth/validate_email/"
    methods: [ "POST" ]
    description: "Validate email"

  register:
    path: "/auth/register/"
    methods: [ "POST" ]
    description: "User registration"

  login:
    path: "/auth/login/"
    methods: [ "POST" ]
    description: "User login"

  send_verification_email:
    path: "/auth/send_verification_email/"
    methods: [ "POST" ]
    description: "Send verifiaction email or for reverification"

  send_reset_password_email:
    path: "/auth/send_reset_password_email/"
    methods: [ "POST" ]
    description: "Send reset password email"

  retrieve_greeting_messages:
    path: "/retrieve_greeting_messages/"
    methods: [ "GET" ]
    description: "Retrieve new greeting messages"

  protected_root:
    path: "/protected/"
    methods: [ "GET" ]
    description: "Protected root"

  upload_test_set:
    path: "/upload/test_set/"
    methods: [ "POST" ]
    description: "Upload test set (for testing purpose)"

  upload_train_set:
    path: "/upload/train_set/"
    methods: [ "POST" ]
    description: "Upload train set"

  predict:
    path: "/predict/"
    methods: [ "POST" ]
    description: "Predict"

  predict_proba:
    path: "/predict_proba/"
    methods: [ "POST" ]
    description: "Predict probability"

  get_data_summary:
    path: "/get_data_summary/"
    methods: [ "GET" ]
    description: "Get a summary of all uploaded data"

  download_all_data:
    path: "/download_all_data/"
    methods: [ "GET" ]
    description: "Download all uploaded data"

  delete_dataset:
    path: "/delete_dataset/"
    methods: [ "DELETE" ]
    description: "Delete dataset (can be train set or test set)"

  delete_all_datasets:
    path: "/delete_all_datasets/"
    methods: [ "DELETE" ]
    description: "Delete all datasets (both train set and test set)"

  delete_user_account:
    path: "/delete_user_account/"
    methods: [ "DELETE" ]
    description: "Delete user account, alongside all associated data"

